portfolio/core/urls.py
from django.urls import path
from .import views
urlpatterns = [
    path('', views.home, name="home"),
    path('posts/', views.posts, name="posts"),
    path('post/<str:pk>', views.post, name="post")
    # path('', views.home, name="home")
    
]

portfolio/portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls'))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

portfolio/core/models.py
from django.db import models

# Create your models here.
class Skills(models.Model):
    skill = models.CharField(max_length=50, unique=True)
    url = models.URLField()

    def __str__(self):
        return self.skill

class Tag(models.Model):
	name = models.CharField(max_length=200)

	def __str__(self):
		return self.name
class Post(models.Model):

    headline = models.CharField(max_length=200)
    created = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=False)
    featured = models.BooleanField(default=False)
    body = models.TextField(null=True, blank=True)
    url = models.URLField(default="https://google.com")
    tags = models.ManyToManyField(Tag, null=True, blank=True)
    overview = models.TextField(null=True, blank=True)
    github = models.URLField(default="https://google.com")

	
    def __str__(self):
        return self.headline

portfolio/core/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import  Skills, Post
from .filters import  PostFilter

def home(request):
    posts = Post.objects.filter(active=True, featured=True)[0:6]
    skills = Skills.objects.all()
    context = {'posts':posts, 'skills':skills}
    
    return render(request, 'core/index.html', context)

def posts(request):
    posts = Post.objects.all()
    myfilter = PostFilter(request.GET, queryset=posts)
    posts = myfilter.qs
    context = {'posts':posts, 'myfilter': myfilter}

    return render(request, 'core/posts.html', context)

def post(request, pk):
    post = Post.objects.get(pk=pk)
    context = {'post': post}
    return render(request, 'core/post.html', context)
# def profile(request):
#     return HttpResponse('<h2>Profile title</h2>')

portfolio/core/templates/core/home.html
{% extends 'core/layout.html' %}

{% block content %}
<h1>Home!!</h1>
{% endblock content %}

portfolio/core/templates/core/index.html
{% extends 'core/layout.html' %}
{% load static %} 
{% block content %}
        <main class="l-main">
            <!--===== HOME =====-->
            <section class="home bd-grid" id="home">
                <div class="home__data">
                    <h3 class="home__title">Hi,<br>I'am <span class="home__title-color">Tejas</span><br> Software Engineer</h3>

                    <a href="{% url 'home' %}#contact" class="button">Contact</a>
                </div>

                <div class="home__social">
                    <a href="" class="home__social-icon-instagram"><i class='bx bxl-instagram' style=" width: 1em; display: inline-block;"></i></a>
                    <a href="" class="home__social-icon-facebook"><i class='bx bxl-facebook'></i></a>
                    <a href="" class="home__social-icon-linkedin"><i class='bx bxl-linkedin' ></i></a>
                    <a href="" class="home__social-icon-github"><i class='bx bxl-github' ></i></a>
                    <a href="" class="home__social-icon-gmail"><i class="material-icons">mail_outline</i></a>
               
                </div>
                
                <div class="home__img">    
                    <img src="assets/img/perfil.png" alt="">
                </div>
            </section>

            <!--===== ABOUT =====-->
            <section class="about section " id="about">
                <h2 class="section-title">About</h2>

                <div class="about__container bd-grid">
                    <div class="about__img">
                        <img src="{% static 'img/work1.jpg' %}" alt="">
                    </div>
                    
                    <div>
                        <h2 class="about__subtitle">I'am Tejas</h2>
                        <p class="about__text">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptate cum expedita quo culpa tempora, assumenda, quis fugiat ut voluptates soluta, aut earum nemo recusandae cumque perferendis! Recusandae alias accusamus atque.</p>           
                    </div>                                   
                </div>
            </section>
           
            <!--===== SKILLS =====-->
            <section class="skills section" id="skills">
                <h2 class="section-title">Skills</h2>

                <div class="skills__container bd-grid">          
                    <div>
                        <h2 class="skills__subtitle">Profesional Skills</h2>
                        <p class="skills__text">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Velit optio id vero amet, alias architecto consectetur error eum eaque sit.</p>
                        
                        <section class="card-list">
                            {% for skill in skills %}
                                <article class="card">
                                    <header class="card-header">  
                                        <a class="image-logo" href="">
                                            <img src="{{skill.url}}">
                                        </a>                                                                                                       
                                    <h2>{{skill.skill}}</h2>                
                                    </header>               
                                </article>
                            {% endfor %}
                                               
                        </section>                       
                        </div>
                    </div>
                    
                </div>
            </section>

            <!--===== WORK =====-->

            <section class="work section"  id="work">
              
                    
                    <a href="{% url 'posts' %}"><h2 class="section-title">Projects</h2></a>
        
                    <div class="work__container bd-grid">
                        {% for post in posts %}
                        
                       <div class="work__img">
                                <a href="{%  url 'post' post.id %}"><img src="{{post.url}}" alt=""></a>
                                <div class="post-preview">
                                    <h4 class="post-title">{{post.headline}}</h4>
                                    <p class="post-intro">{{post.overview}}</p>                                 
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                    <p align="center">
                        <a href="{% url 'posts' %}">View More</a>
                    </p>
            
            </section>
            <!--===== CONTACT =====-->
            <section class="contact section" id="contact">
                <h2 class="section-title">Contact</h2>

                <div class="contact__container bd-grid">
                    <form action="" class="contact__form">
                        <input type="text" placeholder="Name" class="contact__input">
                        <input type="mail" placeholder="Email" class="contact__input">
                        <textarea name="" id="" cols="0" rows="10" class="contact__input"></textarea>
                        <input type="button" value="Enviar" class="contact__button button">
                    </form>
                </div>
            </section>
        </main>

{% endblock content %}

portfolio/core/templates/core/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <link rel="stylesheet" href="{% static 'css/style.css' %}">

        <!-- =====BOX ICONS===== -->
        <link href='https://cdn.jsdelivr.net/npm/boxicons@2.0.5/css/boxicons.min.css' rel='stylesheet'>
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <style type="text/css">
            .footer {
                background-color: #17141d;
                color: #fff;
                text-align: center;
                font-weight: var(--font-semi);
                padding: 1rem 0;
              }
        </style>
        <title>Portfolio website complete</title>
        
    </head>
<body>
    {% include 'core/navbar.html' %}
    {% block content %}
    <!-- CONTENT -->
    {% endblock content %}

    <!--===== FOOTER =====-->
    <footer class="footer">
    
        <p>&#169; 2020 copyright all right reserved</p>
    </footer>

  <!--===== SCROLL REVEAL =====-->
  <script src="https://unpkg.com/scrollreveal"></script>

  <!--===== MAIN JS =====-->
  <script src="{% static 'js/main.js' %}"></script>
</body>
</html>

portfolio/core/templates/core/navbar.html
<!--===== HEADER =====-->
<header class="l-header">
    <nav class="nav bd-grid">
        <div>
            <a href="#" class="nav__logo">Tejas</a>
        </div>

        <div class="nav__menu" id="nav-menu">
            <ul class="nav__list">
                <li class="nav__item"><a href="{% url 'home' %}#home" class="nav__link active">Home</a></li>
                <li class="nav__item"><a href="{% url 'home' %}#about" class="nav__link">About</a></li>
                <li class="nav__item"><a href="{% url 'home' %}#skills" class="nav__link">Skills</a></li>
                <li class="nav__item"><a href="{% url 'home' %}#work" class="nav__link">Work</a></li>
                <li class="nav__item"><a href="{% url 'home' %}#contact" class="nav__link">Contact</a></li>
            </ul>
        </div>

        <div class="nav__toggle" id="nav-toggle">
            <i class='bx bx-menu'></i>
        </div>
    </nav>
</header>

portfolio/core/templates/core/post.html
{% extends 'core/layout.html' %}
{% load static %}
{% block content %}


<section class="post section">
    <h2 class="section-title">{{post.headline}}</h2>

    <div class="post__container">
        <div class="post__img">
            <img src="{{post.url}}" alt="">
        </div>
 
        {% for tag in post.tags.all %} 
                    <span class="tag-post">{{tag}}</span>
         {% endfor %}  
        <hr>
        <div>
            <h2 class="post__subtitle">Project Line</h2>
            <p class="post__text">{{post.overview}}</div>
        <div>
            <h2 class="post__subtitle">Project Overview</h2>
            <p class="post__text">{{post.body}}</div>
        </div>
    </div>
       
  
</section>

{% endblock content %}

portfolio/core/templates/core/posts.html
{% extends 'core/layout.html' %}
{% load static %} 
{% block content %}
{% load crispy_forms_tags %}

<!--===== SEARch=====-->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style type="text/css"> 
    #id_tags{
        max-height: 100px;
        overflow-y: scroll;
        border: 1px solid #888;
        border-radius: 5px;
        padding:5px;
    }
   
    #id_headline{
        width: 100%;
        font-size: 12px;
        font-weight: var(--font-semi);
        padding: 1rem;
        border-radius: .5rem;
        border: 1.5px solid #888;
        outline: none;
        margin-bottom: var(--mb-4);
    }
    #id_headline:hover{
        transform: scale(1.02);
        transition: 0.5s;

    }
    .contact__form{
        width: 760px;
      }
    .work{
padding-top: 1rem;
      }
      .contact__button{
        margin-top: 15px;
      }

</style>
<section class="contact section bd-grid">
    <h2 class="section-title">Search</h2>

    <div class="contact__container bd-grid">
        <form  method="GET" action="" class="contact__form">
            {{myfilter.form|crispy}}
            <!-- <input type="text" placeholder="Search" class="contact__input"> -->
            <input type="submit" value="Search" class="contact__button button">
           

        </form>
    </div>
    
</section>
<section class="work section">
              
    <h2 class="section-title">Projects</h2>

    <div class="work__container bd-grid">
    {% for post in posts %}    
    
       <div class="work__img">
                <a href="{%  url 'post' post.id %}"><img src="{{post.url}}" alt=""></a>
                <div class="post-preview">
                    <h4 class="post-title">{{post.headline}}</h4>
                    <p class="post-intro">{{post.overview}}</p> 
                  
                    <a class="link" href="{%  url 'post' post.id %}">Read More</a>  
                    <hr>
                    {% for tag in post.tags.all %} 
                    <span class="tag">{{tag}}</span>
                    {% endfor %}                          
                </div>
            </div>
        {% endfor %}
    </div>

   

</section>

{% endblock content %}